### ISSUE TITLE
ISP/Country Unknown

### ISSUE THREAD

**Issue by Katiasantos87p** [dvygolov/YellowCloaker#33]
I would like to ask why my cloak appears as unknown?
And how to fix it?

![image](https://user-images.githubusercontent.com/125196435/224392300-c570941c-5eb3-4911-bec6-2fb218999f1e.png)

**Comment by dvygolov** [comment]
That's because this address (all three lines are from the same IPv6
address) is not in MaxMind's database. You can do nothing about it, the
only thing that you can - is to regulary update the database from the
MaxMind's website.

P.S. Btw, other services also don't know anything about this address.
https://whatismyipaddress.com/ip/2001:db8::ff00:42:8329
https://www.ip2location.com/demo/2001:0db8:0000:0000:0000:ff00:0042:8329
